---
title: "expert_elicitation_instructions"
format: html
---

# **Rare California Seabird Distribution Expert Elicitation Exercise**

Thank you for helping us with this work! We hope that this exercise should take you less than an hour to complete. Please read the instructions below carefully before filling out your responses in the spreadsheet that has been provided to you via email.

## Purpose/Application

### Project Context

There are multiple components of vulnerability to offshore wind energy for seabird species. We have existing tools that help us identify where birds are (i.e., SDMs such as [Leirness et al., 2021](https://repository.library.noaa.gov/view/noaa/49073)), how sensitive birds may be to collision or displacement impacts (i.e., vulnerability indices such as Kelsey et al., 2018), and ways of describing bird population status (i.e., IUCN Red List status, state and federal listings, etc). There have also been efforts to combine these metrics in various ways for various purposes, primarily for facility site selection decisions (e.g., the [refinement](https://www.boem.gov/boem_2024-015) of the [now-halted](https://www.boem.gov/renewable-energy/state-activities/Oregon) wind energy lease areas in Oregon). However, these tools have typically been produced on regional scales – we saw a need to develop a tool that could combine these existing understandings of the components of vulnerability to wind energy development to rank species vulnerability based on the placement of lease areas in any given region developing wind energy. Our primary purpose of the tool is to prioritize species for compensatory mitigation/offsetting projects by understanding which species are most vulnerable to impact, however, by helping categorize species vulnerability for given leases this tool could also be used to prioritize research and monitoring projects. The purpose of this paper is two-fold – my goal is to create an approach to combine these metrics of vulnerability that can be applied to any region developing offshore wind energy, and then demonstrate the application of the tool by using it to provide priority rankings for species in the California Current Ecosystem based on the currently identified offshore wind development areas on the Pacific Outer Continental Shelf (POCS).  

### Utility of Expert Elicitation Exercise

We are using the [Leirness et al., 2021](https://repository.library.noaa.gov/view/noaa/49073) species distribution maps of seabirds on the POCS to inform how exposed seabirds in the region will be to the proposed wind energy development areas. These models were produced based on bird sighting data from historical surveys and a range of temporal and spatial environmental predictor variables. Models were not produced for any seabird species that had less than 100 transect segments that contained observations in the historical data, meaning that models were not produced for rare species in the California Current Ecosystem. In cases where that is simply because a species' distribution does not overlap significantly with the POCS region, it is likely fine to leave them out of the prioritization exercise for the region. However, for species of conservation concern that are rare in the region due in part to poor population status, the absence of distribution data creates issues. We are therefore requesting your help in estimating the distributions of three threatened species (Short-tailed Albatross, Hawaiian Petrel, and Townsend's Storm Petrel) that are found in small numbers in the POCS region so that we may include them in the prioritization exercise.

## Instructions

The Leirness et al. (2021) species distribution maps of seabirds on the Pacific Outer Continental Shelf were produced by season when enough data was present for a given species and season to produce a raster map with an estimate of density per km\^2 grid cell. To assess exposure over the course of the entire year, we have combined the models for each season available (assuming a zero presence in seasons not modeled) into an annual model. We then overlay the vector outlines of the wind energy areas under consideration and calculate what proportion much of the summed regional density is found within the development zones. Based on the way that the models are produced and the seasons are combined, this answer cannot be used to predict an actual number of individuals in any given grid cell, but can instead be interpreted as “*In seasons that a species is present in the Pacific Outer Continental Shelf region, what proportion of the use of the region for that species overlaps with the development areas*”.
